package com.lanou.ourteam.mirrors.imagedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanou.ourteam.mirrors.imagedao.MrtjItemEntity;
import com.lanou.ourteam.mirrors.imagedao.GoodsItemEntity;
import com.lanou.ourteam.mirrors.imagedao.StoryItemEntity;
import com.lanou.ourteam.mirrors.imagedao.MenuItemEntity;

import com.lanou.ourteam.mirrors.imagedao.MrtjItemEntityDao;
import com.lanou.ourteam.mirrors.imagedao.GoodsItemEntityDao;
import com.lanou.ourteam.mirrors.imagedao.StoryItemEntityDao;
import com.lanou.ourteam.mirrors.imagedao.MenuItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mrtjItemEntityDaoConfig;
    private final DaoConfig goodsItemEntityDaoConfig;
    private final DaoConfig storyItemEntityDaoConfig;
    private final DaoConfig menuItemEntityDaoConfig;

    private final MrtjItemEntityDao mrtjItemEntityDao;
    private final GoodsItemEntityDao goodsItemEntityDao;
    private final StoryItemEntityDao storyItemEntityDao;
    private final MenuItemEntityDao menuItemEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mrtjItemEntityDaoConfig = daoConfigMap.get(MrtjItemEntityDao.class).clone();
        mrtjItemEntityDaoConfig.initIdentityScope(type);

        goodsItemEntityDaoConfig = daoConfigMap.get(GoodsItemEntityDao.class).clone();
        goodsItemEntityDaoConfig.initIdentityScope(type);

        storyItemEntityDaoConfig = daoConfigMap.get(StoryItemEntityDao.class).clone();
        storyItemEntityDaoConfig.initIdentityScope(type);

        menuItemEntityDaoConfig = daoConfigMap.get(MenuItemEntityDao.class).clone();
        menuItemEntityDaoConfig.initIdentityScope(type);

        mrtjItemEntityDao = new MrtjItemEntityDao(mrtjItemEntityDaoConfig, this);
        goodsItemEntityDao = new GoodsItemEntityDao(goodsItemEntityDaoConfig, this);
        storyItemEntityDao = new StoryItemEntityDao(storyItemEntityDaoConfig, this);
        menuItemEntityDao = new MenuItemEntityDao(menuItemEntityDaoConfig, this);

        registerDao(MrtjItemEntity.class, mrtjItemEntityDao);
        registerDao(GoodsItemEntity.class, goodsItemEntityDao);
        registerDao(StoryItemEntity.class, storyItemEntityDao);
        registerDao(MenuItemEntity.class, menuItemEntityDao);
    }
    
    public void clear() {
        mrtjItemEntityDaoConfig.getIdentityScope().clear();
        goodsItemEntityDaoConfig.getIdentityScope().clear();
        storyItemEntityDaoConfig.getIdentityScope().clear();
        menuItemEntityDaoConfig.getIdentityScope().clear();
    }

    public MrtjItemEntityDao getMrtjItemEntityDao() {
        return mrtjItemEntityDao;
    }

    public GoodsItemEntityDao getGoodsItemEntityDao() {
        return goodsItemEntityDao;
    }

    public StoryItemEntityDao getStoryItemEntityDao() {
        return storyItemEntityDao;
    }

    public MenuItemEntityDao getMenuItemEntityDao() {
        return menuItemEntityDao;
    }

}
