package com.lanou.ourteam.mirrors.imagedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MENU_ITEM_ENTITY".
 */
public class MenuItemEntity {

    private Long id;
    private String title;
    private String topColor;
    private String buttomColor;
    private String type;
    private String info_data;
    private String store;

    public MenuItemEntity() {
    }

    public MenuItemEntity(Long id) {
        this.id = id;
    }

    public MenuItemEntity(Long id, String title, String topColor, String buttomColor, String type, String info_data, String store) {
        this.id = id;
        this.title = title;
        this.topColor = topColor;
        this.buttomColor = buttomColor;
        this.type = type;
        this.info_data = info_data;
        this.store = store;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTopColor() {
        return topColor;
    }

    public void setTopColor(String topColor) {
        this.topColor = topColor;
    }

    public String getButtomColor() {
        return buttomColor;
    }

    public void setButtomColor(String buttomColor) {
        this.buttomColor = buttomColor;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getInfo_data() {
        return info_data;
    }

    public void setInfo_data(String info_data) {
        this.info_data = info_data;
    }

    public String getStore() {
        return store;
    }

    public void setStore(String store) {
        this.store = store;
    }

}
