package com.lanou.ourteam.mirrors.imagedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MRTJ_ITEM_ENTITY".
 */
public class MrtjItemEntity {

    private Long id;
    private String goods_img;
    private String goods_name;
    private String goods_price;
    private String produce_area;
    private String brand;

    public MrtjItemEntity() {
    }

    public MrtjItemEntity(Long id) {
        this.id = id;
    }

    public MrtjItemEntity(Long id, String goods_img, String goods_name, String goods_price, String produce_area, String brand) {
        this.id = id;
        this.goods_img = goods_img;
        this.goods_name = goods_name;
        this.goods_price = goods_price;
        this.produce_area = produce_area;
        this.brand = brand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGoods_img() {
        return goods_img;
    }

    public void setGoods_img(String goods_img) {
        this.goods_img = goods_img;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_price() {
        return goods_price;
    }

    public void setGoods_price(String goods_price) {
        this.goods_price = goods_price;
    }

    public String getProduce_area() {
        return produce_area;
    }

    public void setProduce_area(String produce_area) {
        this.produce_area = produce_area;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

}
